
app:
  port: "5000"

db:
  name: "wgkqvvpe"
  user: "wgkqvvpe"
  port: "5432"
  host: "abul.db.elephantsql.com"

lambda:
  putFile: "put_file"
  pseudoDelete: "pseudo_delete"

yandex:
  storageURL: "https://storage.yandexcloud.net/sancho-stage/static/images/"