DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "category" CASCADE;
DROP TABLE IF EXISTS "products" CASCADE;
DROP TABLE IF EXISTS "sessions" CASCADE;
DROP TABLE IF EXISTS "misc" CASCADE;
DROP TABLE IF EXISTS "orders" CASCADE;
DROP TABLE IF EXISTS "marks" CASCADE;

DROP TYPE IF EXISTS "pay";
DROP TYPE IF EXISTS "order_status";